### ISSUE TITLE
Separating the branch  

### ISSUE THREAD

**Issue by Hemil96** [Hemil96/bookstore-api-nodejs-tutorial#4]
@dlmarrero I think we should have a completely different branch for the client-server app. And master branch will contain only the tutorial's code. Because I believe that mixing the client and server in the master branch will confuse the tutorial followers. What are your thoughts?

**Comment by dlmarrero** [comment]
Makes sense. Your master branch is still unaltered on my fork. If you like, I can submit two new PRs - one with only the changes to the server (to be merged into master) and another with client-server changes (to be merged into a new branch).

The only catch may be that maintenance gets a little trickier. Anytime you make an update to the server side code on the master branch, you’ll have to check out the client branch and pull in the new changes there as well.
> @dlmarrero I think we should have a completely different branch for the client-server app. And master branch will contain only the tutorial's code. Because I believe that mixing the client and server in the master branch will confuse the tutorial followers. What are your thoughts?

**Comment by Hemil96** [comment]
@dlmarrero  Lets do that. Btw I am not going to make any changes on the server now. My next tutorial will have the different repository.

**Comment by dlmarrero** [comment]
@Hemil96 Ok. So do you want me to still make those PRs or should I wait until then?

**Comment by Hemil96** [comment]
@dlmarrero Yes we need to get back the old server in master branch as I have uploaded the postman screenshots as well with old booksModel field. So it is necessary to get the old server back in master branch. 

Needs to be done:
1. Old master branch as it was 
2. new branch containing new server(model modified) and client

**Comment by Hemil96** [comment]
conflicts are there

**Comment by dlmarrero** [comment]
Ok @Hemil96  merge conflicts are fixed in #6
